#!/bin/bash
# creatation: 2020-1-29

# Stop on error
set -e

###
### call_KAS-seq_peaks.sh - This script is used to call peaks for KAS-seq data.
### bed files or indexed bam files are needed.
###
### Usage:
### regular peaks: call_KAS-seq_peaks.sh <KAS_seq_files> <Input_files> <regular> <basename> <genome_size>
### broad peaks: call_KAS-seq_peaks.sh <KAS_seq_files> <Input_files> <broad> <basename> <genome_size>
###
### Example:
### nohup call_KAS-seq_peaks.sh KAS_seq_files.txt Input_files.txt regular KAS-seq_regular hg &
### nohup call_KAS-seq_peaks.sh KAS_seq_files.txt Input_files.txt broad KAS-seq_broad hg &
###
### Options:
### <KAS_seq_files> Input the text file containing the name of KAS-seq IP bed or indexed bam files generated by map_KAS-seq.sh.
### Example: KAS.rep1.bed/bam KAS.rep2.bed/bam KAS.rep3.bed/bam ---KAS_seq_files.txt
###
### <Input_files> Input the text file containing the name of KAS-seq Input bed or indexed bam files..
### Example: Input.rep1.bed/bam Input.rep2.bed/bam Input.rep3.bed/bam ---Input_files.txt
###
### <regular_or_broad> Specify regular or broad to tell macs2 that if put nearby highly enriched regions into a broad region with loose cutoff.
###
### <basename> Input the basename of output files.
###
### <genome_size> Input mappable genome size or effective genome size which is defined as the genome size which can be sequenced(hs, mm, ce, dm).
### Note: hs for Homo sapiens, mm for Mus musculus, ce for Caenorhabditis elegans, dm for Drosophila melanogaster.
###
### -h or --help Print the help.
###


if [[ "$#" -lt 5 ]]; then
  echo
  echo "This script is used to call peaks for KAS-seq data"
  echo "Bed files or indexed KAS-seq Bam files are needed"
  echo
  echo "Usage:
  regular peaks: call_KAS-seq_peaks.sh <KAS_seq_files> <Input_files> <regular> <basename> <genome_size>
  broad peaks: call_KAS-seq_peaks.sh <KAS_seq_files> <Input_files> <broad> <basename> <genome_size>"
  echo " "
  echo "Example: 
  regular peaks: nohup call_KAS-seq_peaks.sh KAS_seq_files.txt Input_files.txt regular KAS-seq_regular hg &
  broad peaks: nohup call_KAS-seq_peaks.sh KAS_seq_files.txt Input_files.txt broad KAS-seq_broad hg &"
  echo
fi


if test -z $1 
then
	echo "please input the text file containing the name of KAS-seq IP bed or indexed bam files generated by map_KAS-seq.sh." 
   exit
fi

if test -z $2
then
   echo "please input the text file containing the name of KAS-seq Input bed or indexed bam files generated by map_KAS-seq.sh."
   exit
fi 

if test -z $3
then
   echo "please specify regular or broad to tell macs2 that if put nearby highly enriched regions into a broad region with loose cutoff"
   exit
fi

if [[ $3 != "regular" ]] && [[ $3 != "broad" ]]
then
   echo "Error: unsupported types of peaks $3"
   exit
fi


if test -z $4
then
   echo "please input the basename of output files."
   exit
fi

if test -z $5
then
   echo "please input mappable genome size or effective genome size which is defined as the genome size which can be sequenced(hs, mm, ce, dm)."
   echo "Note: hs for Homo sapiens, mm for Mus musculus, ce for Caenorhabditis elegans, dm for Drosophila melanogaster."
   exit
fi

KAS_seq_files=$(cat $1)
Input_files=$(cat $2)
regular_or_broad=$3
basename=$4
genome_size=$5

######################################################
echo "  "
echo "Welcom to call KAS-seq peaks with macs2... "
echo "  "

if [[ "${regular_or_broad}" == "regular" ]]; then
macs2 callpeak -t $KAS_seq_files -c $Input_files -g $genome_size -n ${basename}_regular -q 0.01 

elif [[ "${regular_or_broad}" == "broad" ]]; then
macs2 callpeak -t $KAS_seq_files -c $Input_files -n ${basename}_broad --broad -g $genome_size --broad-cutoff 0.01 -q 0.01

fi

echo "=== All done successfully."
