#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'ATAC-seq==0.1','console_scripts','SAMtoBED'
__requires__ = 'ATAC-seq==0.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('ATAC-seq==0.1', 'console_scripts', 'SAMtoBED')()
    )
